### ISSUE TITLE
Component not working on recent SFDC versions

### ISSUE THREAD

**Issue by R9CdMX2L** [rdehler/IP-Ranges#1]
From the SF release notes: 

"In Summer ’15 we will start removing unsupported code from HTML Area home page components. As a result, components that contain JavaScript, CSS, iframes, or other unsupported markup might stop working properly. To use JavaScript or other advanced HTML elements in your home page component, we recommend that you use a Visualforce Area component instead."

**Comment by viraj89** [comment]
Hi @R9CdMX2L !!

There is work around here - https://github.com/rdehler/IP-Ranges/issues/2

Please check if that's working for you.

**Comment by rdehler** [comment]
Permanent solution: this repository is to be retired, use this instead: https://github.com/rdehler/sfdc-whitelist-ips-chrome
